pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
# Install and cache specified node version. Should match version in .nvmrc.
- task: NodeTool@0
  inputs:
    versionSpec: '8.12.0'
# Build the react client.
- script: cd $(Build.Repository.LocalPath)/Scheduler/Client; npm install; npm run build:prod;
  displayName: 'Webpack Build'
# Build the .NET project.
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
# Publish the .NET project (with references client build).
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
# Publish the zipped application build.
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
