pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  displayName: 'Install and cache required node/npm version.'
  inputs:
    # Should match version in .nvmrc.
    versionSpec: '8.12.0'
- task: CmdLine@2
  displayName: 'Change Directory to Client.'
  inputs:
    script: cd $(Build.Repository.LocalPath)/Scheduler/Client
    failOnStderr: true
- task: CmdLine@2
  displayName: 'Install node_modules.'
  inputs:
    script: npm install
    failOnStderr: true
- task: CmdLine@2
  displayName: 'Build react client with webpack.'
  inputs:
    script: npm run build:prod
    failOnStderr: true
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
